#!/usr/bin/env bash
# =============================================================================
# Self-inflatable archive — auto-generated by Gradle assembleDist task
#
# Usage:
#   bash HALDiSh-<version>.run [--prefix <install-dir>]
#
# Options:
#   --prefix <dir>   Install scripts to <dir>  (default: ~/.local/lib/haldish)
#   --list           List archive contents without installing
#   --help           Show this help
# =============================================================================
set -euo pipefail

ARCHIVE="$0"
DEFAULT_PREFIX="${HOME}/.local/lib/haldish"

_usage() {
    sed -n '/^# Usage:/,/^# ===/{ /^# ===/d; s/^# \{0,2\}//; p }' "$ARCHIVE"
    exit 0
}

_extract() {
    local prefix="$1"
    local payload_line
    payload_line=$(awk '/^__PAYLOAD_BEGIN__$/{print NR+1; exit}' "$ARCHIVE")

    if [[ -z "$payload_line" ]]; then
        echo "ERROR: archive payload not found — file may be corrupted." >&2
        exit 1
    fi

    echo "Installing HALDiSh scripts to: ${prefix}"
    mkdir -p "$prefix"

    tail -n +"$payload_line" "$ARCHIVE" \
        | base64 -d \
        | tar -xzf - -C "$prefix"

    local setup="${prefix}/setup.sh"
    if [[ -f "$setup" ]]; then
        bash "$setup" "$prefix"
    fi
    exit 0
}

_list() {
    local payload_line
    payload_line=$(awk '/^__PAYLOAD_BEGIN__$/{print NR+1; exit}' "$ARCHIVE")
    tail -n +"$payload_line" "$ARCHIVE" | base64 -d | tar -tzf -
    exit 0
}

# ── argument parsing ──────────────────────────────────────────────────────────
PREFIX="$DEFAULT_PREFIX"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --prefix)   PREFIX="$2"; shift 2 ;;
        --prefix=*) PREFIX="${1#*=}"; shift ;;
        --list)     _list ;;
        --help|-h)  _usage ;;
        *)
            echo "Unknown option: $1" >&2
            echo "Run with --help for usage." >&2
            exit 1
            ;;
    esac
done

_extract "$PREFIX"

# The lines below this comment are the base64-encoded payload.
# Do NOT edit manually.
