#!/usr/bin/env bash
# =============================================================================
# adoc.sh — emit AsciiDoc tagged regions from grouped files
#
# Usage:
#   adoc.sh [-a <file>] [<base>...] [-- <ext>...]
#   printf "base1\nbase2\n" | adoc.sh [-a <file>] [-- <ext>...]
#
# For each base name, finds all files matching <base>.* in the current
# directory and wraps their content in AsciiDoc tagged regions:
#
#   // tag::<filename-with-ext>[]
#   <raw file content>
#   // end::<filename-with-ext>[]
#
# Base names come from the positional arguments before "--"; when none are
# given there, they are read from stdin (one per line).
#
# Extension filter: everything after "--" is a list of extensions to document
# (e.g. "-- body headers" emits only <base>.body and <base>.headers).  A leading
# dot is optional (body and .body are equivalent).  With no "--" (or a bare "--"
# with nothing after it) all extensions are documented, as before.  Files are
# emitted in glob (sorted) order regardless of the order extensions are listed.
# A requested extension with no matching <base>.<ext> file warns (per base) but
# does not change the exit status.
#
# Options:
#   -a <file>   Append AsciiDoc content to <file> instead of stdout.
#               In this mode the base name is printed to stdout (for piping).
#
# Designed to work with httpreq.sh output groups (.curl, .status, .headers,
# .cookies, .body), but accepts any file groups.
#
# Stdout: AsciiDoc tagged regions (default) or base name per processed group (-a mode)
# =============================================================================
set -euo pipefail

_usage() {
    printf 'Usage: %s [-a <file>] [<base>...] [-- <ext>...]\n' "$(basename "$0")" >&2
    printf '       printf "base1\\nbase2\\n" | %s [-a <file>] [-- <ext>...]\n' "$(basename "$0")" >&2
}

. hal_utils.sh

_append_file=''

# Parse -a option before base names / stdin
if [[ $# -gt 0 && "$1" == '-a' ]]; then
    if [[ $# -lt 2 ]]; then
        printf '%s: -a requires a filename\n' "$(basename "$0")" >&2
        exit 1
    fi
    _append_file="$2"
    shift 2
fi

declare -a _bases=()
declare -a _exts=()

# Split the remaining arguments at "--": bases before, extension filter after.
while [[ $# -gt 0 ]]; do
    if [[ "$1" == '--' ]]; then
        shift
        _exts=( "$@" )
        break
    fi
    _bases+=( "$1" )
    shift
done

# A leading dot on an extension is optional: .body and body are equivalent.
for _i in "${!_exts[@]}"; do
    _exts[_i]="${_exts[_i]#.}"
done

# No bases on the command line → read them from stdin (one per line).
if [[ ${#_bases[@]} -eq 0 && ! -t 0 ]]; then
    while IFS= read -r _line; do
        [[ -z "$_line" ]] && continue
        _bases+=( "$_line" )
    done
fi

# No bases and stdin is interactive (nothing piped) is a usage error; an empty
# pipe just yields no work (exit 0, as before).
if [[ ${#_bases[@]} -eq 0 && -t 0 ]]; then
    _usage; exit 1
fi

shopt -s nullglob

# _emit <base>
# Uses the global _exts[] array as an extension filter (empty = all extensions).
_emit() {
    local base="$1"
    local files=( "${base}".* )

    # With a filter, warn for every requested extension that has no <base>.<ext>.
    if [[ ${#_exts[@]} -gt 0 ]]; then
        local e
        for e in "${_exts[@]}"; do
            [[ -e "${base}.${e}" ]] || hal::log::warn "${base} has no .${e}" >&2
        done
    fi

    # Select the files to emit, keeping glob (sorted) order.  No filter → all.
    local -a sel=()
    local f
    for f in ${files[@]+"${files[@]}"}; do
        if [[ ${#_exts[@]} -eq 0 ]]; then
            sel+=( "$f" )
        else
            local ext="${f#"${base}".}" e keep=0
            for e in "${_exts[@]}"; do
                [[ "$ext" == "$e" ]] && { keep=1; break; }
            done
            [[ $keep -eq 1 ]] && sel+=( "$f" )
        fi
    done

    if [[ ${#sel[@]} -gt 0 ]]; then
        printf '== %s\n\n' "$base"
        for f in "${sel[@]}"; do
            printf '=== %s\n\n' "$f"
            printf '[source]\n----\n'
            printf '// tag::%s[]\n' "$f"
            cat -- "$f"
            [ -z "$(tail -c 1 "$f")" ] || printf '\n'
            printf '// end::%s[]\n----\n' "$f"
        done
    fi
}

for base in "${_bases[@]}"; do
    if [[ -n "$_append_file" ]]; then
        [ -s "$_append_file" ] || (
            printf '= ASCIIDoc regions generated by HALDiSh toolkit\n:toc: left\n\n' >> "$_append_file"
            printf 'File of samples regions, generated by https://github.com/C06A/HALDiSh.git[HALDiSh toolkit]\n\n' >> "$_append_file"
        )

        hal::log::info "append to $_append_file files $base.*" >&2

        _emit "$base" >> "$_append_file"
        printf '%s\n' "$base"
    else
        _emit "$base"
    fi
done
