#!/usr/bin/env bash
# =============================================================================
# adoc.sh — emit AsciiDoc tagged regions from grouped files
#
# Usage:
#   adoc.sh [-a <file>] <base>...
#   printf "base1\nbase2\n" | adoc.sh [-a <file>]
#
# For each base name, finds all files matching <base>.* in the current
# directory and wraps their content in AsciiDoc tagged regions:
#
#   // tag::<filename-with-ext>[]
#   <raw file content>
#   // end::<filename-with-ext>[]
#
# Options:
#   -a <file>   Append AsciiDoc content to <file> instead of stdout.
#               In this mode the base name is printed to stdout (for piping).
#
# Designed to work with httpreq.sh output groups (.curl, .status, .headers,
# .cookies, .body), but accepts any file groups.
#
# Stdout: AsciiDoc tagged regions (default) or base name per processed group (-a mode)
# =============================================================================
set -euo pipefail

_usage() {
    printf 'Usage: %s [-a <file>] <base>...\n' "$(basename "$0")" >&2
    printf '       printf "base1\\nbase2\\n" | %s [-a <file>]\n' "$(basename "$0")" >&2
}

. hal_utils.sh

_append_file=''

# Parse -a option before base names / stdin
if [[ $# -gt 0 && "$1" == '-a' ]]; then
    if [[ $# -lt 2 ]]; then
        printf '%s: -a requires a filename\n' "$(basename "$0")" >&2
        exit 1
    fi
    _append_file="$2"
    shift 2
fi

declare -a _bases=()

if [[ $# -gt 0 ]]; then
    _bases=( "$@" )
elif [[ ! -t 0 ]]; then
    while IFS= read -r _line; do
        [[ -z "$_line" ]] && continue
        _bases+=( "$_line" )
    done
else
    _usage; exit 1
fi

shopt -s nullglob

_emit() {
    local base="$1"
    local files=( "${base}".* )
    if [[ ${#files[@]} -gt 0 ]]; then
        printf '== %s\n\n' "$base"
        for f in "${files[@]}"; do
            printf '=== %s\n\n' "$f"
            printf '[source]\n----\n'
            printf '// tag::%s[]\n' "$f"
            cat -- "$f"
            [ -z "$(tail -c 1 "$f")" ] || printf '\n'
            printf '// end::%s[]\n----\n' "$f"
        done
    fi
}

for base in "${_bases[@]}"; do
    if [[ -n "$_append_file" ]]; then
        [ -s "$_append_file" ] || (
            printf '= ASCIIDoc regions generated by HALDiSh toolkit\n:toc: left\n\n' >> "$_append_file"
            printf 'File of samples regions, generated by https://github.com/C06A/HALDiSh.git[HALDiSh toolkit]\n\n' >> "$_append_file"
        )

        hal::log::info "append to $_append_file files $base.*" >&2

        _emit "$base" >> "$_append_file"
        printf '%s\n' "$base"
    else
        _emit "$base"
    fi
done
